# Generated by Django 3.2 on 2021-04-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_id'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='ids',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='registration.registration'),
        ),
    ]
